# .github/workflows/trigger-pages.yml
name: Trigger GitHub Pages sync

on:
  push:
    paths:
      - 'docs/cv_fr.html'
      - 'docs/cv_en.html'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync in .github.io repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAGES_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Vincent-Mouillot/Vincent-Mouillot.github.io/actions/workflows/sync.yml/dispatches \
            -d '{"ref":"main"}'
